### PR TITLE
Fixes #4 null object reference exception

### LINKED ISSUE #4: Extension UnixTimeToDateTime doesn't check for null value
when the string is not initialized yet (means that the field doesn't have a value) a null object reference exception occurs.

### PR DESCRIPTION
**Pull request by mkeymolen**
Pull request to fix the unixtoDatetime extension #4  and the implementation for #6 .
Also added a throttling mechanism #8  because of the limited calls to teamleader

### CODE REVIEW

File: src/TeamleaderDotNet/Utils/UnixTimestampExtensions.cs [hunk 1]
```diff
@@ -44,7 +44,7 @@ public static DateTime UnixTimeToDateTime(this int unixtime)
         /// <returns>Returns a DateTime object that represents value of the Unix time.</returns>
         public static DateTime UnixTimeToDateTime(this string unixtime)
         {
-            return UnixTimeToDateTime(long.Parse(unixtime.ToString()));
+            return !string.IsNullOrEmpty(unixtime) ? UnixTimeToDateTime(long.Parse(unixtime)) : DateTime.MinValue;
```
Comment (jeroenverh) [inline src/TeamleaderDotNet/Utils/UnixTimestampExtensions.cs]: Wouldn't it be nicer if we return NULL instead of DateTime.MinValue (or make another extension method so that we can support both cases). For me it feels more natural that something without date is NULL instead of DateTime.MinValue. This would have the effect though that some of properties will also be changed in the future to nullable types - so not that great for backwards compatibility.

Comment (mkeymolen) [reply src/TeamleaderDotNet/Utils/UnixTimestampExtensions.cs]: yes you are correct. I was already testing my implementation for custom fields and there i needed to convert unixtime to datetime but the value of the custom field was null so i had an error.. i'll update the pull request in a moment. thanks for the fast review and great work. It helped me already a lot. As soon as i have some time left, i'll do some other pull request in future.

Comment (mkeymolen) [reply src/TeamleaderDotNet/Utils/UnixTimestampExtensions.cs]: @jeroenverh
The problem is however, if teamleader returns an empty unixdatetime, the UnixDateConverter does not achieve in converting the value to a datetime. If you want that behaviour, you need to modify to a nullable datetime like a did with deals. I didn't modify exisiting classes. You can do that but then you need to create a new major version, which is not needed for this pull request. Can you please create a new nuget package? Thanks!

**Comment by jeroenverh** [comment]
PR has been merged - nuget v1.0.37 has been published!

**Comment by mkeymolen** [comment]
Great! thanks for the fast review/merge. It's very motivating to continue working on this project
